=== Levermann/LisasProjekt/Projekt/Semester6/ITT/MarkUpLanguages/strongValidateLectureDescriptionSpeech.dtd
<?xml version='1.0' encoding='UTF-8'?>
        <!---Exercise 2 XML & DTDs d) This DTD File describes some stronger validation for VLML-->
        <!ELEMENT Vorlesung (Titel, Hochschule*, SWS, Semester, Kapitel+, Quelle+)>
        <!ELEMENT Titel (#PCDATA)>
        <!ELEMENT Semester (#PCDATA)>
        <!ELEMENT Hochschule (#PCDATA)>
        <!ELEMENT SWS (#PCDATA)>
        <!ELEMENT Kapitel (Name,Termin+)>
        <!ATTLIST Kapitel nummer CDATA #REQUIRED>
        <!ATTLIST Kapitel quelle IDREF #REQUIRED>
        <!ATTLIST Kapitel bewertung CDATA "1">
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Termin (#PCDATA)>
        <!ELEMENT Quelle (Autor+,Titel, SourceType)>
        <!ATTLIST Quelle quellenID ID #REQUIRED>

        <!ELEMENT SourceType (#PCDATA)>
        <!ATTLIST SourceType sourceSpecies (Monographie| Artikel| Dissertation| Abschlussarbeit) #REQUIRED>

        <!ELEMENT Autor (#PCDATA)>
        <!ELEMENT Monographie (#PCDATA)>
        <!ELEMENT Artikel (#PCDATA)>
        <!ELEMENT Dissertation (#PCDATA)>
        <!ELEMENT Abschlussarbeit (#PCDATA)>

=== Levermann/LisasProjekt/Projekt/Semester6/ITT/MarkUpLanguages/strongLectureDescriptionSpeech.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Vorlesung SYSTEM "strongValidateLectureDescriptionSpeech.dtd">
<!--- Exercise 2 XML & DTDs validate created XML File
use strongValidateLectureDescriptionSpeech7.dtd for strictly validating XML -->
<Vorlesung>
    <Titel>Software Engineering</Titel>
    <Hochschule>Landshut</Hochschule>
    <SWS>20</SWS>
    <Semester>Sommersemester</Semester>
    <Kapitel nummer="9" quelle="QDEA" >
        <Name>Deterministische Automaten</Name>
        <Termin>08.12.2020</Termin>
    </Kapitel>
    <Kapitel nummer="8" quelle="QRE" bewertung="34">
        <Name>Requirements Engineering</Name>
        <Termin>09.12.2020</Termin>
        <Termin>10.12.2020</Termin>
    </Kapitel>
    <Quelle quellenID="QDEA" >
        <Autor>Student xy</Autor>
        <Titel>Wikipedia</Titel>
        <SourceType sourceSpecies="Monographie"/>
    </Quelle>
    <Quelle quellenID="QRE">
        <Autor>Scholz</Autor>
        <Titel>Deterministische Automaten</Titel>
        <SourceType sourceSpecies="Dissertation"/>
    </Quelle>
</Vorlesung>
