=== Levermann/LisasProjekt/Projekt/Semester6/ITT/XMLSchemaDefinition/vorlesung.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="Vorlesung">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Titel" type="xsd:string"></xsd:element>
                <xsd:element name="Semester" type="xsd:string" maxOccurs="unbounded"></xsd:element>
                <xsd:element name="Hochschule" type="xsd:string"></xsd:element>
                <xsd:element name="SWS" type="xsd:int"></xsd:element>
                <xsd:element name="Kapitel" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Name" type="xsd:string"></xsd:element>
                            <xsd:element name="Termin" type="xsd:int" maxOccurs="unbounded"></xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="nummer" type="xsd:int"></xsd:attribute>
                        <xsd:attribute name="quelle" type="xsd:IDREFS"></xsd:attribute>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Quelle">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Autor" type="xsd:string" maxOccurs="unbounded"></xsd:element>
                            <xsd:element name="Titel" type="xsd:string"></xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="quellenID" type="xsd:ID"></xsd:attribute>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Levermann/LisasProjekt/Projekt/Semester6/ITT/XtensibleMarkupLanguage/vorlesung.xml
<?xml version="1.0" encoding="UTF-8"?>
<Vorlesung
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../XMLSchemaDefinition/vorlesung.xsd">
    <Titel>Internettechnologien</Titel>
    <Semester> Sommersemester </Semester>
    <Hochschule> HAW Landshut </Hochschule>
    <SWS> 4 </SWS>
    <?myTool align=left?> <!-- Anweisung an myTool-->
    <Kapitel nummer="1">
        <Name>Einf√ºhrung</Name>
        <Termin> 1 </Termin>
    </Kapitel>
    <Kapitel nummer="2" quelle="Q1">
        <Name>Grundlagen von Netzwerken</Name>
        <Termin> 2 </Termin>
    </Kapitel>
    <Kapitel nummer="3">
        <Name>XML</Name>
        <Termin> 4 </Termin>
    </Kapitel>
    <Kapitel nummer="4">
        <Name>HTML &amp; CSS</Name>
        <Termin> 7 </Termin>
    </Kapitel>
    <Quelle quellenID="Q1">
        <Autor> Balzert, Helmut</Autor>
        <Titel> Lehrbuch der SW-Technik</Titel>
    </Quelle>
</Vorlesung>
