=== Levermann/LisasProjekt/Projekt/Semester6/ITT/XMLSchemaDefinition/votingValidation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:simpleType name="percent" id="percent">
        <xsd:restriction base="xsd:decimal">
            <xsd:fractionDigits value="2"/>
            <xsd:minInclusive value="0" id="percent.minInclusive"/>
            <xsd:maxInclusive value="100" id="percent.maxInclusive"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:element name="Wahl">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Wahltag" type="xsd:date"></xsd:element>
                <xsd:element name="Wahlbeginn" type="xsd:time"></xsd:element>
                <xsd:element name="Wahlende" type="xsd:time"></xsd:element>
                <xsd:element name="Parteien" minOccurs="2" maxOccurs="100">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Name"></xsd:element>
                            <xsd:element name="Kandidaten" minOccurs="3" maxOccurs="25">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Name" type="xsd:string"></xsd:element>
                                        <xsd:element name="Geburtsdatum" type="xsd:date"></xsd:element>
                                        <xsd:element name="Beruf" type="xsd:string" maxOccurs="unbounded"></xsd:element>
                                        <xsd:element name="Listenplatz" type="xsd:string"></xsd:element>
                                        <xsd:element name="Erststimmen" type="percent"></xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="ergebnis" type="xsd:IDREFS"></xsd:attribute>
                        <xsd:attribute name="isBundesweit" type="xsd:boolean"></xsd:attribute>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Wahlergebnis">
                    <xsd:complexType mixed="true">
                        <xsd:choice>
                            <xsd:element name="Zweitstimme" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:simpleContent>
                                        <xsd:extension base="percent">
                                            <xsd:attribute name="partei" type="xsd:ID"/>
                                        </xsd:extension>
                                    </xsd:simpleContent>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="wahltyp">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="Landtagswahl"/>
                        <xsd:enumeration value="Bundestagswahl"/>
                        <xsd:enumeration value="Europawahl"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Levermann/LisasProjekt/Projekt/Semester6/ITT/XtensibleMarkupLanguage/voting.xml
<?xml version="1.0" encoding="UTF-8"?>
<Wahl
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../XMLSchemaDefinition/votingValidation.xsd">
    <Wahltag>2001-12-26</Wahltag>
    <Wahlbeginn>08:45:02</Wahlbeginn>
    <Wahlende>18:00:00</Wahlende>
    <Parteien ergebnis="IDE" isBundesweit="false">
        <Name>EinfÃ¼hrung</Name>
        <Kandidaten>
            <Name>Hans</Name>
            <Geburtsdatum>2001-10-26</Geburtsdatum>
            <Beruf>Handweker aus Leidenschaft</Beruf>
            <Listenplatz>1</Listenplatz>
            <Erststimmen>70.8</Erststimmen>
        </Kandidaten>
        <Kandidaten>
            <Name>sepp</Name>
            <Geburtsdatum>2002-10-09-11:00</Geburtsdatum>
            <Beruf>Tierarzt aus Leidenschaft</Beruf>
            <Listenplatz>144</Listenplatz>
            <Erststimmen>10.8</Erststimmen>
        </Kandidaten>
        <Kandidaten>
            <Name>Paulina</Name>
            <Geburtsdatum>2002-10-09-11:00</Geburtsdatum>
            <Beruf>Tierarzt aus Leidenschaft</Beruf>
            <Listenplatz>144</Listenplatz>
            <Erststimmen>10.8</Erststimmen>
        </Kandidaten>
    </Parteien>
    <Parteien ergebnis="PHPMyAdmin" isBundesweit="false">
        <Name>EinfÃ¼hrung</Name>
        <Kandidaten>
            <Name>Hans</Name>
            <Geburtsdatum>2001-12-26</Geburtsdatum>
            <Beruf>Handweker aus Leidenschaft</Beruf>
            <Listenplatz>1</Listenplatz>
            <Erststimmen>70.8</Erststimmen>
        </Kandidaten>
        <Kandidaten>
            <Name>Felix</Name>
            <Geburtsdatum>2002-10-09-11:00</Geburtsdatum>
            <Beruf>Tierarzt aus Leidenschaft</Beruf>
            <Listenplatz>144</Listenplatz>
            <Erststimmen>10.8</Erststimmen>
        </Kandidaten>
        <Kandidaten>
            <Name>Natalie</Name>
            <Geburtsdatum>2002-10-09-11:00</Geburtsdatum>
            <Beruf>Tierarzt aus Leidenschaft</Beruf>
            <Listenplatz>144</Listenplatz>
            <Erststimmen>10.8</Erststimmen>
        </Kandidaten>
    </Parteien>
    <Wahlergebnis>
        <Zweitstimme partei="IDE">22.5</Zweitstimme>
        <Zweitstimme partei="PHPMyAdmin">88.5</Zweitstimme>
    </Wahlergebnis>
</Wahl>
