=== Levermann/LisasProjekt/Projekt/Semester6/ITT/XtensibleStylesheetLanguage/BookTransformXml/book1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Book (Autor, title, toc, chapter+)>
<!ELEMENT Autor (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT toc (entry)+>
<!ELEMENT entry (#PCDATA)>
<!ATTLIST entry id IDREF #REQUIRED>
<!ELEMENT chapter (title, text)>
<!ATTLIST chapter id ID #REQUIRED>
<!ELEMENT text (#PCDATA)>

=== Levermann/LisasProjekt/Projekt/Semester6/ITT/XtensibleStylesheetLanguage/BookTransformXml/myBook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!---We want to be able to validate this xml with book2.dtd
We need a XSLT transformation to generate a new XML-file: myBook2.xml witch is matching to book2.dtd
USE: java -jar xalan-j_2_7_2\xalan.jar -IN myBook.xml -XSL transformXML.xsl -OUT myBook2.xml -DIAG
0:55 min
-->
<!DOCTYPE Book SYSTEM 'Book1.dtd'>

<Book>
    <Autor>Homer J. Simpson</Autor>
    <title> Einführung in XSLT</title>
    <toc>
        <entry id="c1"> Einführung</entry>
        <entry id="c2"> Ende</entry>
    </toc>
    <chapter id="c1"> 
        <title> Einführung </title>
        <text>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.

            Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, 
        </text>
    </chapter>
    <chapter id="c2">
        <title>Ende </title>
        <text> Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.

            Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, 
        </text>
    </chapter>
    
</Book>
